# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'falconrypro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Networking'
  pod 'PKHUD', '~> 4.0'
  pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git'
  pod 'SDWebImage', '~>4.0'
  pod 'Reveal-SDK', :configurations => ['Debug']
  pod "Sparrow/Modules/RequestPermission", :git => "https://github.com/IvanVorobei/Sparrow.git"
  pod 'UIEmptyState'
  pod 'MiniTabBar'
  pod 'FastEasyMapping', '~> 1.1'
  pod 'Validator', '~> 2.1.1'
  pod 'FBSDKLoginKit', '4.18.0'
  pod 'Charts'
  pod 'RoundedSwitch'
  pod 'ImageRow', :git => 'https://github.com/EurekaCommunity/ImageRow.git'
  pod 'SwiftDate', '~> 4.0'
  pod 'UICountingLabel'
  pod 'BadgeSwift', '~> 5.0'
  pod 'PureLayout'
  pod 'SwiftRichString'
  pod 'SwipeCellKit'
  pod 'EZYGradientView', :git => 'https://github.com/Niphery/EZYGradientView'

  pod 'Mapbox-iOS-SDK', '~> 3.5.4'

  target 'falconryproTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'falconryproUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
