# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'falconrypro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Fabric'
pod 'Crashlytics'
pod 'Networking'
pod 'pop', '~> 1.0'
pod 'PKHUD', '~> 5.0'
#pod 'Eureka'
pod 'SDWebImage', '~>4.0'
pod 'UIEmptyState'
pod 'FastEasyMapping', '~> 1.2'
pod 'Validator'
pod 'FBSDKLoginKit', '~> 5.0'
pod 'Charts', '~> 3.3'
pod 'ImageRow', '~> 4.0'
pod 'SwiftDate', '~> 6.0'
pod 'UICountingLabel'
pod 'BadgeSwift', '~> 8.0'
pod 'PureLayout'
pod 'SwiftRichString'
pod 'SwipeCellKit', '2.5.4'
pod 'SwiftLocation', '~> 4.0'
pod 'Mapbox-iOS-SDK', '~> 4.10'
pod "Solar"
pod 'AIFlatSwitch', '~> 1.0.6'
pod 'CHTCollectionViewWaterfallLayout/Swift'
pod 'TagListView', '~> 1.0'
pod 'JBKenBurnsView'



end
