# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'falconrypro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Fabric'
  pod 'Crashlytics'
  pod "ILLoginKit"
  pod 'Networking'
  pod 'PKHUD', '~> 4.0'
  pod 'Eureka', '~> 2.0'
  pod 'ImageRow', '~> 1.0'
  pod 'SDWebImage', '~>4.0'
  pod 'Reveal-SDK', :configurations => ['Debug']

  target 'falconryproTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'falconryproUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
